UserParameter=speedtest.download,/usr/local/bin/zbx-speedtest.sh download
UserParameter=speedtest.upload,/usr/local/bin/zbx-speedtest.sh upload
UserParameter=speedtest.ping,/usr/local/bin/zbx-speedtest.sh ping
UserParameter=speedtest.jitter,/usr/local/bin/zbx-speedtest.sh jitter
UserParameter=speedtest.packetloss,/usr/local/bin/zbx-speedtest.sh packetloss
UserParameter=speedtest.server.id,/usr/local/bin/zbx-speedtest.sh server-id
UserParameter=speedtest.server.name,/usr/local/bin/zbx-speedtest.sh server-name
UserParameter=speedtest.server.location,/usr/local/bin/zbx-speedtest.sh server-location
UserParameter=speedtest.isp,/usr/local/bin/zbx-speedtest.sh isp
UserParameter=speedtest.wan.ip,/usr/local/bin/zbx-speedtest.sh external-ip
UserParameter=speedtest.age,/usr/local/bin/zbx-speedtest.sh age
